version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
