apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: message-app
  template:
    metadata:
      labels:
        app: message-app
    spec:
      containers:
        - name: message-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@db-service:5432/{{ .Values.database.name }}"
            - name: RABBITMQ_URL
              value: "amqp://{{ .Values.rabbitmq.user }}:{{ .Values.rabbitmq.password }}@rabbitmq-service:5672/"