apiVersion: v1
kind: Service
metadata:
  name: message-app
spec:
  selector:
    app: message-app-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: {{ .Values.service.type }}